name: 'Docker build and push'
on:
  # Trigger the action manually from the UI
  push:
    paths:
      - 'node_red/*'

jobs:
  build_docker_images:
    # Job name that shows in the GitHub UI
    name: Build Docker Images
    # Runner to use
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
