name: 'Terraform'
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose plan or apply or destroy'
        required: true
        default: 'plan'
        type: choice
        options:
          - apply
          - destroy
          - plan
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.IAM_ROLE_TO_ASSUME }}
        role-session-name: ${{ github.run_id }}
        aws-region: eu-north-1
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
     
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      if: inputs.action == 'plan'
      run: terraform plan -input=false

    - name: Terraform Destroy
      # if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'\
      if: inputs.action == 'destroy'
      run: terraform apply -destroy -auto-approve -input=false
      
    - name: Terraform Apply
      if: inputs.action == 'apply'
      run: terraform apply -auto-approve -input=false
